"""Tool factory: expose swarm graph mutation as Agent-callable tools.

Usage
-----
These tools are given to a **coordinator** agent so it can dynamically spawn
worker agents, wire them into the execution graph, and inspect topology at
runtime::

    from modules.llmfetcher.tools.spawn_tools import create_swarm_tools

    coordinator.add_tools(
        create_swarm_tools(
            swarm=my_swarm,
            llm_fetcher=llm_fetcher,
            worker_tool_pool=global_tools,
        )
    )
"""

from __future__ import annotations

import json
import uuid
from typing import Any, Callable

from ..agent import Agent
from ..llm_fetcher import LLMFetcher
from ..llm_types import Tool, ToolParameter, ToolSchema
from ..swarm_module.swarm import AgentSwarm
from ..swarm_module.task_bus import TaskAssignment


def create_swarm_tools(
    swarm: AgentSwarm,
    llm_fetcher: LLMFetcher,
    worker_tool_pool: list[Tool],
    coordinator_name: str = "main_agent",
    worker_max_rounds: int = 30,
    worker_max_tokens: int = 32768,
    worker_max_context_threshold: int = 262144,
    context_path_factory: Callable[[str], Any] | None = None,
) -> list[Tool]:
    """Create tools that let a coordinator LLM manipulate the swarm at runtime.

    Args:
        swarm:
            The running swarm instance. The coordinator must be registered
            in this swarm so its tool calls can mutate the graph.
        llm_fetcher:
            Shared ``LLMFetcher`` used to create new worker ``Agent``
            instances.
        worker_tool_pool:
            Tools that are registered on every worker created by the
            coordinator.
        coordinator_name:
            Logical coordinator name used as the default structured-report
            recipient for ``dispatch_subagent``.
        worker_max_rounds:
            Default model-and-tool step budget for every worker created by
            these tools.
        worker_max_tokens:
            Default generated-token budget per worker model step.
        worker_max_context_threshold:
            Character count at which every dynamically created worker
            compacts its older conversation history.
        context_path_factory:
            Optional callback returning a durable context path for each
            dynamically created worker Agent.

    Returns:
        A list of ``Tool`` instances the coordinator can call.

    Raises:
        ValueError: If the worker execution budgets or context threshold are
            outside their supported ranges.
    """
    if worker_max_rounds <= 0:
        raise ValueError("worker_max_rounds must be greater than zero")
    if worker_max_tokens <= 0:
        raise ValueError("worker_max_tokens must be greater than zero")
    if worker_max_context_threshold < 1024:
        raise ValueError("worker_max_context_threshold must be at least 1024")

    def _dynamic_add_agent(**kwargs: Any) -> str:
        """Create and register a new worker agent in the swarm.

        Each new agent receives the shared *worker_tool_pool* and a
        customized system *prompt*.

        Required parameters: ``name`` (unique agent name), ``system_prompt``.
        """
        name: str = kwargs.get("name", "")
        system_prompt: str = kwargs.get("system_prompt", "")

        if not name or not system_prompt:
            return "Error: both 'name' and 'system_prompt' are required."

        agent = Agent(
            llm_fetcher=llm_fetcher,
            system_prompt=system_prompt,
            max_context_threshold=worker_max_context_threshold,
            context_path=context_path_factory(name) if context_path_factory else None,
            default_max_rounds=worker_max_rounds,
            default_max_tokens=worker_max_tokens,
        )
        agent.add_tools(worker_tool_pool)

        return swarm.dynamic_add_agent(name, agent)

    def _report_task_tool(
        task_id: str,
        reporter: str,
        on_report: Callable[[], None],
    ) -> Tool:
        """Build the only result-return path available to one dispatched worker.

        Args:
            task_id: Immutable task identifier assigned to the worker.
            reporter: Logical worker name attached to the report.
            on_report: Callback requesting worker completion after the
                structured report is accepted.

        Returns:
            Tool definition that submits a bounded structured report.
        """
        def _report_task(**kwargs: Any) -> str:
            """Submit one structured report without exposing raw run output.

            Args:
                **kwargs: Status, summary, evidence, artifact, and follow-up
                    fields generated by the worker Agent.

            Returns:
                Compact report acknowledgement for the worker context.
            """
            def as_list(value: Any) -> list[str]:
                """Normalize one schema field into string list form.

                Args:
                    value: Model-supplied scalar or sequence value.

                Returns:
                    List of normalized non-empty strings.
                """
                if isinstance(value, list):
                    return [str(item) for item in value]
                return [str(value)] if value else []

            report = swarm.report_task(
                task_id=task_id,
                reporter=reporter,
                status=str(kwargs.get("status", "completed")),
                summary=str(kwargs.get("summary", "")),
                findings=as_list(kwargs.get("findings", [])),
                evidence=as_list(kwargs.get("evidence", [])),
                artifacts=as_list(kwargs.get("artifacts", [])),
                open_questions=as_list(kwargs.get("open_questions", [])),
                recommended_next_action=str(kwargs.get("recommended_next_action", "")),
            )
            on_report()
            return f"Report submitted for task {report.task_id} to {report.recipient}."

        return Tool(
            name="report_task",
            description=(
                "Submit the final structured task report. Do not paste raw "
                "tool output or reasoning; reference detailed files in artifacts. "
                "This is terminal: the worker stops after this tool batch."
            ),
            schemas=ToolSchema(properties=[
                ToolParameter(name="status", type="string", enum=["completed", "failed", "partial"], default="completed", description="Terminal task status."),
                ToolParameter(name="summary", type="string", description="Concise conclusion for the coordinator."),
                ToolParameter(name="findings", type="array", description="Key claims or observations."),
                ToolParameter(name="evidence", type="array", description="URLs or concise evidence references."),
                ToolParameter(name="artifacts", type="array", description="Paths or IDs of persisted detailed output."),
                ToolParameter(name="open_questions", type="array", description="Unresolved follow-up questions."),
                ToolParameter(name="recommended_next_action", type="string", description="Suggested coordinator follow-up."),
            ]),
            handler=_report_task,
        )

    def _dispatch_subagent(**kwargs: Any) -> str:
        """Create, task, and immediately schedule one independent worker.

        Args:
            **kwargs: Worker identity, system prompt, objective, handoff, and
                optional report-recipient fields supplied by the coordinator.

        Returns:
            Task identifier and worker name for a later ``wait_for_reports`` call.
        """
        try:
            assignment = _create_assignment(kwargs)
        except ValueError as exc:
            return f"Error: {exc}"
        return (
            f"Dispatched {assignment.recipient} with task_id={assignment.id}. "
            "Call wait_for_reports with this task_id before synthesizing results."
        )

    def _create_assignment(specification: dict[str, Any]) -> TaskAssignment:
        """Create one worker and its explicit task assignment from a tool spec.

        Args:
            specification: Model-provided worker name, prompt, objective,
                handoff, report recipient, and artifact expectations.

        Returns:
            Accepted task assignment from the shared swarm task bus.

        Raises:
            ValueError: If required fields are missing or the graph rejects
                the requested worker identity.
        """
        name = str(specification.get("name", "")).strip()
        system_prompt = str(specification.get("system_prompt", "")).strip()
        objective = str(specification.get("objective", "")).strip()
        handoff = str(specification.get("handoff", "")).strip()
        reply_to = str(specification.get("reply_to", coordinator_name)).strip() or coordinator_name
        expected_artifacts = specification.get("expected_artifacts", [])
        if isinstance(expected_artifacts, str):
            expected_artifacts = [expected_artifacts]
        if not isinstance(expected_artifacts, list):
            raise ValueError("expected_artifacts must be an array")
        if not name or not system_prompt or not objective:
            raise ValueError("name, system_prompt, and objective are required")
        task_id = uuid.uuid4().hex
        worker = Agent(
            llm_fetcher=llm_fetcher,
            system_prompt=system_prompt,
            max_context_threshold=worker_max_context_threshold,
            context_path=context_path_factory(name) if context_path_factory else None,
            default_max_rounds=worker_max_rounds,
            default_max_tokens=worker_max_tokens,
        )
        worker.add_tools(
            worker_tool_pool + [_report_task_tool(task_id, name, worker.request_completion)]
        )
        return swarm.dispatch_task(
            agent_name=name,
            agent_instance=worker,
            objective=objective,
            handoff=handoff,
            reply_to=reply_to,
            expected_artifacts=[str(item) for item in expected_artifacts],
            task_id=task_id,
        )

    def _dispatch_subagents(**kwargs: Any) -> str:
        """Dispatch a complete independent worker group in one tool call.

        Args:
            **kwargs: ``assignments`` array containing one task specification
                per worker, plus an optional expected worker count.

        Returns:
            JSON containing every worker name and task ID for one subsequent
            ``wait_for_reports`` call.
        """
        specifications = kwargs.get("assignments", [])
        try:
            expected_count = int(kwargs.get("expected_count", 0))
        except (TypeError, ValueError):
            return "Error: expected_count must be an integer."
        if not isinstance(specifications, list) or not specifications:
            return "Error: assignments must be a non-empty array."
        if expected_count and len(specifications) != expected_count:
            return f"Error: expected exactly {expected_count} assignments."
        if not all(isinstance(specification, dict) for specification in specifications):
            return "Error: every assignment must be an object."
        names = [str(specification.get("name", "")).strip() for specification in specifications]
        if len(names) != len(set(names)) or not all(names):
            return "Error: every assignment needs a unique non-empty name."
        try:
            assignments = [_create_assignment(specification) for specification in specifications]
        except ValueError as exc:
            return f"Error: {exc}"
        return json.dumps(
            {
                "tasks": [
                    {"agent_name": assignment.recipient, "task_id": assignment.id}
                    for assignment in assignments
                ],
            },
            ensure_ascii=False,
        )

    def _wait_for_reports(**kwargs: Any) -> str:
        """Wait for selected worker reports and return their bounded JSON form.

        Args:
            **kwargs: Task ID list and bounded timeout supplied by coordinator.

        Returns:
            JSON object containing received structured reports only.
        """
        task_ids = kwargs.get("task_ids", [])
        if isinstance(task_ids, str):
            task_ids = [task_ids]
        timeout_seconds = max(1.0, min(float(kwargs.get("timeout_seconds", 120.0)), 900.0))
        reports = swarm.wait_for_reports(task_ids, timeout_seconds)
        return json.dumps(
            {"requested_task_ids": task_ids, "reports": [report.as_dict() for report in reports]},
            ensure_ascii=False,
        )

    def _dynamic_add_connection(**kwargs: Any) -> str:
        """Add a directed dependency edge between two agents.

        After this call, *target* waits for *source* to complete before
        it may execute.  The source must not have finished yet.

        Required: ``source``, ``target``.
        """
        source: str = kwargs.get("source", "")
        target: str = kwargs.get("target", "")

        if not source or not target:
            return "Error: both 'source' and 'target' are required."

        return swarm.dynamic_add_connection(source, target)

    def _dynamic_remove_agent(**kwargs: Any) -> str:
        """Remove an agent and every edge connected to it."""
        name: str = kwargs.get("name", "")
        if not name:
            return "Error: 'name' is required."
        return swarm.dynamic_remove_agent(name)

    def _dynamic_remove_connection(**kwargs: Any) -> str:
        """Remove a dependency edge from the editable graph."""
        source = str(kwargs.get("source", ""))
        target = str(kwargs.get("target", ""))
        if not source or not target:
            return "Error: both 'source' and 'target' are required."
        return swarm.dynamic_remove_connection(source, target)

    def _dynamic_set_mapper(**kwargs: Any) -> str:
        """Set a declarative fan-in mapper on a target Agent."""
        agent_name = str(kwargs.get("agent_name", ""))
        mode = str(kwargs.get("mode", "labelled"))
        if not agent_name:
            return "Error: 'agent_name' is required."
        return swarm.dynamic_set_mapper(agent_name, mode)

    def _dynamic_set_router(**kwargs: Any) -> str:
        """Set a fixed successor subset for a source Agent."""
        agent_name = str(kwargs.get("agent_name", ""))
        targets = kwargs.get("targets", [])
        if isinstance(targets, str):
            targets = [targets]
        targets = [str(target) for target in targets]
        if not agent_name:
            return "Error: 'agent_name' is required."
        return swarm.dynamic_set_router(agent_name, targets)

    def _dynamic_get_info(**kwargs: Any) -> str:
        """Return the current graph topology as structured text.

        Useful for inspecting which agents are registered and how they
        are connected before deciding on next steps.
        """
        return swarm.dynamic_get_info()

    return [
        Tool(
            name="dispatch_subagents",
            description=(
                "Dispatch a complete group of independent workers in one call. "
                "Use this for a fixed task list, then pass every returned task "
                "ID to wait_for_reports. Do not wait after dispatching only one worker."
            ),
            schemas=ToolSchema(properties=[
                ToolParameter(name="assignments", type="array", description="Worker task objects: name, system_prompt, objective, handoff, reply_to, expected_artifacts."),
                ToolParameter(name="expected_count", type="integer", default=0, description="Exact required worker count; use it to prevent partial groups."),
            ]),
            handler=_dispatch_subagents,
        ),
        Tool(
            name="dispatch_subagent",
            description=(
                "Dispatch an independent subagent with an explicit objective and "
                "bounded handoff. It runs immediately and returns only a structured "
                "report through wait_for_reports; do not add a dependency edge."
            ),
            schemas=ToolSchema(properties=[
                ToolParameter(name="name", type="string", description="Unique worker name."),
                ToolParameter(name="system_prompt", type="string", description="Worker role and quality constraints."),
                ToolParameter(name="objective", type="string", description="Concrete task assigned only to this worker."),
                ToolParameter(name="handoff", type="string", description="Compact coordinator state relevant to the task."),
                ToolParameter(name="reply_to", type="string", default=coordinator_name, description="Coordinator receiving the structured report."),
                ToolParameter(name="expected_artifacts", type="array", description="Expected detailed-output paths or names."),
            ]),
            handler=_dispatch_subagent,
        ),
        Tool(
            name="wait_for_reports",
            description=(
                "Wait for structured reports from dispatched task IDs. Use this "
                "instead of inspecting subagent raw run output."
            ),
            schemas=ToolSchema(properties=[
                ToolParameter(name="task_ids", type="array", description="Task IDs returned by dispatch_subagent."),
                ToolParameter(name="timeout_seconds", type="number", default=120, description="Maximum wait duration in seconds."),
            ]),
            handler=_wait_for_reports,
        ),
        Tool(
            name="dynamic_add_agent",
            description=(
                "Create and register a new worker agent in the execution graph. "
                "The new agent will receive the shared worker tools (web fetch, "
                "KB read/write, clock).  After creation, connect it to the graph "
                "with dynamic_add_connection."
            ),
            schemas=ToolSchema(
                properties=[
                    ToolParameter(
                        name="name",
                        type="string",
                        description="Unique name for the new agent (e.g. 'worker_mexico'). Must not conflict with existing names.",
                    ),
                    ToolParameter(
                        name="system_prompt",
                        type="string",
                        description="Full system prompt for the new worker agent.",
                    ),
                ],
            ),
            handler=_dynamic_add_agent,
        ),
        Tool(
            name="dynamic_add_connection",
            description=(
                "Add a dependency edge from source to target. "
                "The target agent will not execute until the source has completed. "
                "Connect workers to the coordinator AFTER creating them, so they "
                "run when the coordinator finishes."
            ),
            schemas=ToolSchema(
                properties=[
                    ToolParameter(
                        name="source",
                        type="string",
                        description="Name of the predecessor agent (e.g. 'coordinator').",
                    ),
                    ToolParameter(
                        name="target",
                        type="string",
                        description="Name of the successor agent (e.g. 'worker_mexico').",
                    ),
                ],
            ),
            handler=_dynamic_add_connection,
        ),
        Tool(
            name="dynamic_remove_agent",
            description=(
                "Remove an agent and every edge connected to it from the graph. "
                "Useful to clean up failed or misconfigured workers."
            ),
            schemas=ToolSchema(
                properties=[
                    ToolParameter(
                        name="name",
                        type="string",
                        description="Name of the agent to remove.",
                    ),
                ],
            ),
            handler=_dynamic_remove_agent,
        ),
        Tool(
            name="dynamic_remove_connection",
            description="Remove an existing dependency edge before the graph source completes.",
            schemas=ToolSchema(properties=[
                ToolParameter(name="source", type="string", description="Predecessor Agent name."),
                ToolParameter(name="target", type="string", description="Successor Agent name."),
            ]),
            handler=_dynamic_remove_connection,
        ),
        Tool(
            name="dynamic_set_mapper",
            description=(
                "Configure how a fan-in Agent receives predecessor outputs. "
                "Use labelled for readable evidence, concat for plain text, or json for structured aggregation."
            ),
            schemas=ToolSchema(properties=[
                ToolParameter(name="agent_name", type="string", description="Target Agent receiving gathered outputs."),
                ToolParameter(name="mode", type="string", enum=["labelled", "concat", "json"], default="labelled", description="Declarative aggregation mode."),
            ]),
            handler=_dynamic_set_mapper,
        ),
        Tool(
            name="dynamic_set_router",
            description="Configure a source Agent to activate only the listed successor Agents after completion.",
            schemas=ToolSchema(properties=[
                ToolParameter(name="agent_name", type="string", description="Source Agent name."),
                ToolParameter(name="targets", type="array", description="Successor Agent names to activate."),
            ]),
            handler=_dynamic_set_router,
        ),
        Tool(
            name="dynamic_get_info",
            description=(
                "Inspect the current execution graph: list registered agents, "
                "their connections, and concurrency limits. Useful before "
                "creating or removing workers."
            ),
            schemas=ToolSchema(properties=[]),
            handler=_dynamic_get_info,
        ),
    ]
